services:
  postgres-rag:
    image: pgvector/pgvector:pg16
    container_name: feelog-postgres-rag
    environment:
      POSTGRES_DB: feelog_rag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - feelog-rag-data:/var/lib/postgresql/data
      - ./postgres_rag_setup.sql:/docker-entrypoint-initdb.d/postgres_rag_setup.sql

volumes:
  feelog-rag-data: